esphome:
  name: esphome-name
  friendly_name: RangeTestExample
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    

# Enable logging
logger:

api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxxxx"

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source: /config/my_components
    refresh: always

i2c: 
  sda: GPIO8
  scl: GPIO9
  scan: True
 
sensor:
  - platform: tof_vl53l1x
    name: "Distance"
    update_interval: 250ms
    distance_mode: long
    timing_budget_ms: 150000
    intermeasurement_ms: 250
    filters:
      - sliding_window_moving_average:
          window_size: 3
          send_every: 1
    accuracy_decimals: 0
    unit_of_measurement: "mm"